{% set name = "ccorp-yaml-include-relative-path" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ccorp-yaml-include-relative-path-{{ version }}.tar.gz
  sha256: 08a7ab4438ad30fdbc86e1b97693d5e22197767a9d2b1db2e02d287908c21be3

build:
  noarch: python
  script:
    # patch in LICENSE file
    - curl -sLO https://raw.githubusercontent.com/marsoloGit/ccorp_yaml_include/163789cc516997e033ecc2f488eab2c075c7c66f/LICENSE
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - curl
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ruamel.yaml

test:
  imports:
    - ccorp.ruamel.yaml.include
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marsoloGit/ccorp_yaml_include
  summary: Exactly ccorp-yaml-include package with a bug fix and support of relative paths for included aliases
  license: 'MIT'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewfeickert
